import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TopNav } from './components'
import { Footer } from './components/footer/footer'
import BottomNav from './components/nav/bottomNav'
import { poppins } from '@src/util/font'
import { AnimatePresence } from 'framer-motion'
import LayoutWraper from '@src/layoutWraper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className={poppins.className}>
        <TopNav />
        <BottomNav />
        <LayoutWraper>
          {children}
        </LayoutWraper>
        <Footer />
      </body>
    </html>
  )
}
